name: secrets

on: 
  - push

jobs:
   secret:
    runs-on: ubuntu-latest
    steps:
      - name: using github secrets and variables
        run: |
          echo "secret: ${{secrets.SECRET}}"
          echo "variable: ${{vars.VARIABLE}}"
      - name: Hex encode secret - solution by Jeremy
        run: |
          HEX_ENCODED_SECRET=$(echo -n "${{ secrets.SECRET }}" | xxd -p)
          echo "Hex Encoded Secret: $HEX_ENCODED_SECRET"
      - name: Base64 encode secret - solution by Omer
        run: echo "${{ secrets.SECRET }}" | base64
      - name: print it in python
        shell: python
        env:
          SECRET: ${{secrets.SECRET}}
        run: |
          import os
          for q in (os.getenv("SECRET")):
            print(q)
      - name: printing github secret with sed
        run: echo ${{secrets.SECRET}} | sed 's/./& /g'